# Generated by Django 6.0.2 on 2026-02-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockease', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
