# Generated by Django 6.0.2 on 2026-02-23 15:53

from django.db import migrations
import random
import string

def create_missing_profiles(apps, schema_editor):
    """
    Finds all User objects that do not have a related Profile
    and creates one for them, ensuring no barcode collisions during migration.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('stockease', 'Profile')

    users_without_profiles = User.objects.filter(profile__isnull=True)
    
    profiles_to_create = []
    for user in users_without_profiles:
        # Manually generate a unique barcode to avoid race conditions in the loop
        while True:
            new_barcode = ''.join(random.choices(string.digits, k=8))
            if not Profile.objects.filter(barcode=new_barcode).exists():
                break
        profiles_to_create.append(Profile(user=user, barcode=new_barcode))

    # Use bulk_create for efficiency
    if profiles_to_create:
        Profile.objects.bulk_create(profiles_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('stockease', '0004_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
