# Generated by Django 6.0.2 on 2026-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockease', '0006_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
